# config/app.yaml

# access
access:
  - [ "ACCESS-KEY-ID","ACCESS-KEY-SECRET" ]

# base config
base:
  node: 1
  host: 127.0.0.1
  monitor: 127.0.0.1
  portRpc: 50051

# kafka - message queue
mq:
  - 127.0.0.1:9092

# logs dir
log: /var/zlabms

# broker
broker:
  port: 3000
  login: http://127.0.0.1:3001

# business
business:
  # config for cache
  cache:
    host: 127.0.0.1
    port: 6379

  # config for database
  db:
    redis:
      host: 127.0.0.1
      port: 6379

    mysql:
      host: 127.0.0.1
      port: 3306
      user:
      pass:
      name:

# login service
login:
  port: 3001
